name: Welcome Workflow

on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch

jobs:
  welcome-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Welcome Message
        run: echo "👋 Welcome to the SCM Weather Website project!"

